pipeline {
    agent any

    tools {
        maven 'maven'
    }
	
	environment {
    APP_NAME = "Simple Java CI/CD"
	}

	post {
    always {
        echo 'Pipeline Completed'
    }
	}
    stages {
        stage('Checkout') {
            steps {
                git branch: 'master', url: 'https://github.com/jenkins-docs/simple-java-maven-app.git'
            }
        }

        stage('Build') {
            steps {
                sh 'mvn clean install'
            }
        }

        stage('Test') {
            steps {
                sh 'mvn test'
            }
        }

        stage('Archive Artifact') {
            steps {
                archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true
            }
        }
		stage('Code Quality') {
		steps {
			echo 'Running static code analysis...'
		}
		}
		stage('Show App Name') {
			steps {
				echo "Application Name is: ${APP_NAME}"
			}
		}
    }
}
